language: objective-c 
osx_image: xcode10

script:
  - xcodebuild clean test -project currency_converter/currency_converter.xcodeproj -scheme currency_converter -destination "platform=iOS Simulator,name=iPhone 7,OS=11.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
